### ISSUE TITLE
Game crashes on launch with sound initialization error

### ISSUE THREAD

**Issue by wispborne** [davidwhitman/SMOL#73]
But it works fine when run from IntelliJ...

![image](https://user-images.githubusercontent.com/1343347/156854776-a597ecf9-9d65-4f21-b1e7-4efa39045bf7.png)
![image](https://user-images.githubusercontent.com/1343347/156854782-fe0f6477-eec1-46b0-9a13-89ad7432ce08.png)

**Comment by wispborne** [comment]
```
1897 [Thread-3] ERROR sound.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - org.lwjgl.LWJGLException: Could not locate OpenAL library.
org.lwjgl.LWJGLException: Could not locate OpenAL library.
    at org.lwjgl.openal.AL.create(AL.java:156)
    at org.lwjgl.openal.AL.create(AL.java:102)
    at org.lwjgl.openal.AL.create(AL.java:206)
    at sound.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sound.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.o00000(Unknown Source)
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

```
101398 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalListenerfv(IJ)V
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalListenerfv(IJ)V
    at org.lwjgl.openal.AL10.nalListenerfv(Native Method)
    at org.lwjgl.openal.AL10.alListener(AL10.java:685)
    at sound.OoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.o00000(Unknown Source)
    at com.fs.starfarer.O0OO.L.o00000(Unknown Source)
    at com.fs.starfarer.title.TitleScreenState.advance(Unknown Source)
    at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
    at com.fs.state.AppDriver.begin(Unknown Source)
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by wispborne** [comment]
- Copying `OpenAL64.dll` into `Windows/System32` fixes the crash.
- Renaming/deleting `lwjgl64.dll`, which is in the same folder (`native/windows`) causes the game to crash, implying that that sibling dll is getting loaded even though the OpenAL one isn't.

**Comment by randomguyingithub** [comment]
Can reliably reproduce by launching from SMOL beta01-r3. Launch directly or by MOSS would not result in sound initalization error.

**Comment by wispborne** [comment]
> Can reliably reproduce by launching from SMOL beta01-r3. Launch directly or by MOSS would not result in sound initalization error.

I figured it out late last night and will push an update when I can.

To fix it earlier, you can copy the two OpenAL dlls in `Starsector/starsector-core/native/windows` into your Windows/System32 folder (don't replace anything!). My fix doesn't do that, but when debugging, I noticed that that fixed it. 

Link to fix (also note that this changes SMOL to launch Starsector _directly_, rather than opening the launcher - more investigation will be needed to see if I can do that but maybe my fix will work for both types of launching).
https://github.com/davidwhitman/SMOL/commit/bf8cc0c73c170ec83cd8afaca4932802b1009c2b#diff-758c54208a6acc5771586d50f6c4087c7de9de73cc94acbf8d52f4a2c3f576d4R163

**Comment by rognstad** [comment]
FWIW, I was working through this on my machine last night. After a fresh SS install (after clearing out the old folder), the issue only started after I used SMOL to set vmparams (seemingly regardless of value). When I switched to using a vmparams file from the Discord, I stopped having the problem. Windows 10 19044.1586 here.

**Comment by wispborne** [comment]
Was unable to fix launching the game from SMOL causing strange/crashy behavior, but added a warning and an alternative option of opening the game folder instead.
